name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['core']
    name: Publishing ${{ matrix.package }}
    steps:
      - name: Checkout project repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Publish package on NPM 📦
        run: node ./tools/scripts/publish.js ${{ matrix.package }} ${{ github.event.release.tag_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
